### ISSUE TITLE
can we setup the model used? 

### ISSUE THREAD

**Issue by jairoFernandez** [douglasmakey/shelldon#1]
Is there any way to know which model of openAI I am using? e.g. gpt4, gpt4o, gpt3.5, or some fine tunnning?

https://github.com/douglasmakey/shelldon/blob/main/src/command/mod.rs#L94

**Comment by douglasmakey** [comment]
Hi @jairoFernandez , yes, you can set the model with the `--model` flag, something like `shelldon ask --model gpt3.5 "tell me a joke"`.

**Comment by jairoFernandez** [comment]
if I create a prompt works fine, however if I try to execute the example doesn't work, I guess is a good idea to include some default prompts

![CleanShot 2024-06-04 at 09 16 00@2x](https://github.com/douglasmakey/shelldon/assets/3932407/dc986075-bf50-47e4-9909-b0be0656bf02)

**Comment by douglasmakey** [comment]
Hey @jairoFernandez, I'm glad I was able to help you notice that the examples in the readme were incorrect. To execute that, you need to use the subcommand `exec` so the correct format should be:

```sh
$ shelldon exec "Show all the graphics ports for the Vagrant machine using Libvirt."
```
